# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 'seo title'
email: jgatjens@gmail.com
description: 'Some cool seo description'
author: seoauthor
url: 'http://domain.com'

source: src
destination: dist
baseurl: '' # the subpath of your site, e.g. /blog

# Build settings
markdown: kramdown

gems:
  - jekyll-seo-tag